### ISSUE TITLE
Бинд автоходьбы на кнопку мыши

### ISSUE THREAD

**Issue by TrueLecter** [Kramar1337/GenshinImpact-AHK-flex#1]
Возможно ли вообще? Во всяких ММО биндил автоходьбу на "4-ю клавишу" (та что обычно сбоку). Тут же, даже если напрямую прописать в конфиг код кнопки, работать не хочет

**Comment by Kramar1337** [comment]
genConfig.ini
key_autowalk=XButton1
или
key_autowalk=XButton2
4-5 кнопка на мышке
мышку нельзя через гиу биндить только через конфиг
