### ISSUE TITLE
[Feature Request] Spamclick for upgrading weapon and level exp

### ISSUE THREAD

**Issue by aureliony** [Kramar1337/GenshinImpact-AHK-flex#10]
Would like to request a function to auto spam click materials when upgrading.

**Comment by Kramar1337** [comment]
I am telling you a little secret. The game provides the ability to quickly select materials for weapons and books of experience for characters. No scripts are needed for this. Just hold LMB on the material (don't move the mouse).
[gif](https://giphy.com/gifs/DuQXTGxh5NcrhBkTC7)

**Comment by aureliony** [comment]
Thanks for that, I knew already but it's still too slow for me. No worries though
