### ISSUE TITLE
Проблема с 9N2CJ на Ху Тао

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/GenshinImpact-AHK-flex#11]
Чардж не кастуется поскольку присутствует только два инстанса урона, идут две нормальные и прыжок.
Стоит SendInput.

**Comment by Kramar1337** [comment]
N2CJ - нормал 2 кансел джамп
так и должно быть

**Comment by Dramorian** [comment]
> 

Вот оно что, а я-то думал...

**Comment by Dramorian** [comment]
> N2CJ - нормал 2 кансел джамп так и должно быть

Вот оно что, а я-то думал...

**Comment by Dramorian** [comment]
А сможешь запилить с чарджем?

**Comment by Kramar1337** [comment]
Hu Tao H1CJ - этот для холд тычек

**Comment by Dramorian** [comment]
> Hu Tao H1CJ - этот для холд тычек

С этим тоже что-то не то, не выглядит так будто чардж идёт, идёт только нормальная

**Comment by Kramar1337** [comment]
на обычный режим атаки не работает нужно находиться под пиро инфузией то есть нажать "E" и зажать макро клавишу и пойдет нагиб

**Comment by Dramorian** [comment]
> на обычный режим атаки не работает нужно находиться под пиро инфузией то есть нажать "E" и зажать макро клавишу и пойдет нагиб

Я не настолько глупый, жму R и нагиба нет, Просто даёт нормальную и прыгает. Charged where?

**Comment by Kramar1337** [comment]
по этой ссылке я и калибровал скрипт. проверил у себя, все работает

**Comment by Dramorian** [comment]
> по этой ссылке я и калибровал скрипт. проверил у себя, все работает

если буде время и не лень, то запиши демку, я в недоумении просто.

**Comment by Kramar1337** [comment]
макрос запилил 3 месяца назад, а никто им судя по всему не пользовался. 
на хутаве не играю гифка рядом с N2CJ на имба сайте сбила с толку(там 2 тычки а где холда?).

Я так понимаю этот макрос нужен для челов с С1, у меня нет С1 по этому сложновато калибровать
можешь потыкаться с исходником(покрутить тайминги)
Как это запускать:
по пустому месту на рабочем столе ПКМ => создать => автохоткей скрипт
открыть через блокнот, вставить код ниже и запустить
`key=V
Hotkey, *~%key%, Metka, on
#NoEnv
SendMode Input
SetWorkingDir %A_ScriptDir%
#SingleInstance force
If !(A_IsAdmin)
{
	Run *RunAs "%A_ScriptFullPath%" /restart
	ExitApp
}
Return
;========================================N2CJ(2 удара, холда, джамп)
Metka:
ifWinActive ahk_class UnityWndClass
{
	Loop
	{
	    GetKeyState, SpaceState, %key%, P
		If SpaceState = U
			break
		SendInput {LButton}
		Sleep 200
		SendInput {LButton}
		Sleep 150
		SendInput {LButton down}
		Sleep 350
		SendInput {LButton up}
		SendInput {Space}
		sleep 570
	}
}
return

*~$end::
Exitapp

*~$home::
SoundBeep
Reload
return`

**Comment by Dramorian** [comment]
> Я так понимаю этот макрос нужен для челов с С1

> The currently recommended ones are:
> 
> C1: N1CD+9N2CD+N1CD (1+9+1 combo) 
> C0: 8N2CJ+N1C (8+1 combo)
>  
> 
> Our current ceiling combos are 
> 
> C1:12N2CD (Bowtae combo)
> C0: 9N2CJ (ITZ combo)

**Comment by Dramorian** [comment]
> key=V Hotkey, *~%key%, Metka, on #NoEnv SendMode Input SetWorkingDir %A_ScriptDir% #SingleInstance force If !(A_IsAdmin) { Run *RunAs "%A_ScriptFullPath%" /restart ExitApp } Return ;========================================N2CJ(2 удара, холда, джамп) Metka: ifWinActive ahk_class UnityWndClass { Loop { GetKeyState, SpaceState, %key%, P If SpaceState = U break SendInput {LButton} Sleep 200 SendInput {LButton} Sleep 150 SendInput {LButton down} Sleep 350 SendInput {LButton up} SendInput {Space} sleep 570 } } return
> 
> *~$end:: Exitapp
> 
> *~$home:: SoundBeep Reload return

вроде работает как надо. спаситель.

**Comment by Dramorian** [comment]
> SendInput {LButton}
> Sleep 200
> SendInput {LButton}
> Sleep 150
> SendInput {LButton down}
> Sleep 530
> SendInput {LButton up}
> SendInput {Space}
> sleep 570

520мс пару раз получилось дальше не может, на 530мс идеально без запинок

**Comment by Kramar1337** [comment]
ок, в некст обнове добавлю этот макрос

**Comment by Dramorian** [comment]
> ок, в некст обнове добавлю этот макрос сегодня или завтра

для n1cj аналогично, естественно. просто лишний вызов кнопки убрать.

кстати, находил на днях макрос на сайте botmek (там выкладываются в формате amc для ноунейм софта).
там по какой-то причине для пробела стоит рандомный сон от 42 до 46 мс. есть идеи для чего такое?

**Comment by Kramar1337** [comment]
слишком маленькое значение(42-46) чтобы оно что то решало
в теории рандом может быть нужен для безопасности, но в этой игре он не нужен.
