### ISSUE TITLE
Небольшая хотелка

### ISSUE THREAD

**Issue by CRYSTAF** [Kramar1337/GenshinImpact-AHK-flex#13]
Хотелось бы увидеть функцию смены бинда клавиш макросов, так как переделываю сейчас полностью ваш скрипт под себя, с удалением некоторых не используемых функций, добавлением старых. И невозможность настройки некоторых клавиш приводит меня в очень большое недовольство, так как я перешел со 100% на 65% клавиатуру. Думаю данная настройка поможет многим людям, так как у всех разные клавиатуры, ну и конечно же вам, так как в жизни разные ситуации бывают

**Comment by CRYSTAF** [comment]
[GenshiAHKFlex.zip](https://github.com/Kramar1337/GenshinImpact-AHK-flex/files/8127667/GenshiAHKFlex.zip)
Вот кстати то, что получилось у меня в итоге. Убрал пулемет для лучников, заместо него добавил драгонстрайк на эолу, добавил так же плавание и переназначил все бинды что связаны с нумпадом и таймером, в общем если нажать пкм п иконке скрипта - info там все будет написано

**Comment by Kramar1337** [comment]
Добавлю в некст обнове в .ini файл возможность изменения кнопок. (обнова не скоро, прикручиваю автообновлятор, удаляю неиспользуемые функции)

п.с Была мысль что не у всех полноразмерные клавиатуры и чтото нужно придумать, но других вариантов не вижу, будут новые персонажи а значит и будут добавлены новые скрипты и кнопок не хватит. 
Кста "5 - Включить/отключить банихоп" "Alt + 5 - Klee N1CJ" в игре иногда дают поиграть за пробного персонажа на 5м слоте и получится конфликт.

У меня такой вопрос:
Зачем Юле драгонстрайк? Урона там не много, например у Дилюка при драгонстрайке нет дк статуса и какой-то смысл вроде есть, а у Юлы?
Я както в одной из версий делал драгонстрайк на всех двуруков и копейщиков, весело но "0" профита!
Драгонстрайк срабатывает не всегда по тому что:
У всех противников разные хитбоксы
Разное расстояние между игроком и противником
Бафы скорости(диона, анемо резонанс)
Дебафы скорости(крио слаймы)
Попытка драгонстрайка сопровождается потерей стамины, а в бездне это карается ретраем.
Или я чота не знаю?

**Comment by Kramar1337** [comment]
Добавлю в некст обнове в .ini файл возможность изменения кнопок. (обнова не скоро, прикручиваю автообновлятор, удаляю неиспользуемые функции)

п.с Была мысль что не у всех полноразмерные клавиатуры и чтото нужно придумать, но других вариантов не вижу, будут новые персонажи а значит и будут добавлены новые скрипты и кнопок не хватит. 
Кста "5 - Включить/отключить банихоп" "Alt + 5 - Klee N1CJ" в игре иногда дают поиграть за пробного персонажа на 5м слоте и получится конфликт.

У меня такой вопрос:
Зачем Юле драгонстрайк? Урона там не много, например у Дилюка при драгонстрайке нет дк статуса и какой-то смысл вроде есть, а у Юлы?
Я както в одной из версий делал драгонстрайк на всех двуруков и копейщиков, весело но "0" профита!
Драгонстрайк срабатывает не всегда по тому что:
У всех противников разные хитбоксы
Разное расстояние между игроком и противником
Бафы скорости(диона, анемо резонанс)
Дебафы скорости(крио слаймы)
Попытка драгонстрайка сопровождается потерей стамины, а в бездне это карается ретраем.
Или я чота не знаю?

**Comment by CRYSTAF** [comment]
Я вроде говорил что переделываю скрипт под себя, поэтому мне просто так удобнее :D

**Comment by CRYSTAF** [comment]
А на счет этого: "п.с Была мысль что не у всех полноразмерные клавиатуры и что-то нужно придумать, но других вариантов не вижу, будут новые персонажи а значит и будут добавлены новые скрипты и кнопок не хватит." могу предложить добавление функции включения и отключения некоторых макросов, так как не у каждого человека есть тот или иной персонаж, а вместе с этим появится возможность добавления чекбокса "Нажми сюда, если у тебя нету Numpad'a", при включении которого переназначаются все кнопки с нумпада на другие (к примеру как у меня). А еще я кстати заметил что в игре не так уж и мало неиспользуемых кнопок, а именно: R, T, Y, U, I, [, ], F, H, K, :, ", Z, X, N, ,, ., /, все цифры от 6 до 0, а так же - и =. На все эти клавиши можно вполне переназначить менее используемые функции, так как та же функция рыбалки требует нажатия на нее всего 1(2) раз и не требуется в ситуациях, когда надо быстро принять решение. Я с такой мыслью переназначил таймер(с небольшим костылем(если постараться - можно найти)) с N на vkDD.

**Comment by Kramar1337** [comment]
решение одной проблемы открывает после себя ряд других проблем. если я открою игровой чат или карту и начну писать чтото то начнется перещелкивание макросов. отдельно крутить фильтры не оч удобно, к каждой функции скрипта особый подход к фильтрации, и 20+ макросных переключателей фильтровать душно
добавление в GUI чекбоксов сопровождается болью, у AHK нет норм редактора GUI.

самое простое решение это перенести все кнопки в "genConfig.ini" файл и кому надо тот сам себе настроит.
мне не придется мучать жопу, а челы смогут настроить скрипт под себя

**Comment by CRYSTAF** [comment]
Вам решать

**Comment by CRYSTAF** [comment]
Мое дело было предложить

**Comment by CRYSTAF** [comment]
Хотелось бы еще узнать как можно вернуть Sendplay режим, так как winapi небезопасный, по вашим словам, а sendinput, а слишком медленно реагирует. Я вроде уже в каком топике задавал этот вопрос и все решилось тем, что вы мне посоветовали использовать режим SendPlay, но сейчас вы его убрали и я не понимаю почему, потому что мне он помогал. Он был хотя бы чем-то средним между winapi и sendinput.

**Comment by CRYSTAF** [comment]
"самое простое решение это перенести все кнопки в "genConfig.ini" файл и кому надо тот сам себе настроит.
мне не придется мучать жопу, а челы смогут настроить скрипт под себя" и еще прошу сделать так, чтобы можно было настраивать клавиши по кодам vk или sc, потому что, в скрипте, который скидывал при нажатии кнопки Save в скрипте он просто сбрасывал "vkDD" на стандартную кнопку, так как не видел в "vkDD" клавишу. ну или хотя бы намек как это можно поправить.

**Comment by Kramar1337** [comment]
SendPlay удален из за ненадобности и проблем с докалибровкой других макросов.
SendPlay отправляет нажатие окну и он не может быть быстрее Sendinput.
если Sendinput медленно реагирует значит стоит высокая задержка или же слишком низкая и игра не успевает регистрировать нажатия.
что конкретно работает медленно?

**Comment by Kramar1337** [comment]
+-505 строка "CheckVarKey4MatchList :="
там список допустимых клавиш, я брал с сайта и не проверял

**Comment by CRYSTAF** [comment]
"что конкретно работает медленно?" объясню на простом примере: включаешь WinApi и все работает идеально

**Comment by Kramar1337** [comment]
все как я и говорил
`
DllCall("keybd_event", int, WinApiKey, int, 0xA0, int, 0, int, 0)
sleep 1
DllCall("keybd_event", int, WinApiKey, int, 0xA0, int, 2, int, 0)
`
у винапи режима 15мс(sleep 1) задержка по этому он лучше отрабатывает.
мне нужен конкретный пример в использовании конкретной функции скрипта и что именно медленно работает и в чем это выражается
п.с. весь автохоткей по своей сути обертка над WinApi. Скрипт написан с использованием Sendinput и некоторые фрагменты заменены на вручную расписанный keybd_event и mouse_event который для упрощения я назвал "WinApi режим", у ахк нет своих драйверов и он обращается к OS чтобы сделать те или иные действия. Если игра работает не отзывчиво значит она не успевает обрабатывать нажатия или клики. 55-60фпс в игре есть? проц вывозит игру?

**Comment by Kramar1337** [comment]
1 друг играет с Sendinput режимом
2й друг на ноуте без видяхи с Sendinput
я на WinApi режиме
у всех все норм

**Comment by Kramar1337** [comment]
есть галочка в "настройки => AHK max speed" в выкл положении ставит стандартный приоритет процесса и стандартную скорость выполнения команд, можно ее потыкать и посмотреть на результат

**Comment by CRYSTAF** [comment]
Игра успевает обрабатывать нажатия, т.к. на винапи все норм. При первом запуске скрипта(допустим после перезагрузки ПК) первые пол часа-час(может быть даже всю игру) предметы подбираются очень медленно. Допустим ты зажал F и побежал на кучку предметов и они начинают на столько медленно собираются, что возникает такое чувство, как будто это вручную делается. Отключение AHK msx speed либо не помогло, либо на столько мало, что я этого не вижу.

**Comment by CRYSTAF** [comment]
Поиграл сейчас немного, чтобы убедиться в проблеме скрипта. Вынужден признать, что у меня не всегда идеальные 55-60 фпс, но даже когда 55 и выше фпс просадки в работе скрипта все равно видно и одчень даже хорошо, по сравнению с тем же winapi.

**Comment by Kramar1337** [comment]
такой вариант, найти в коде "Metkakey_fastlyt:" и заменить
multisendinput("sc21", "", "sc21", "", "0x46", "0", "", "")
на 
	SendInput {vk46 Down}
	Sleep 15
	SendInput {vk46 up}
и проверить результат

**Comment by CRYSTAF** [comment]
Вроде помогло, ну в общем протестирую временем.
