### ISSUE TITLE
Еще одно предложение

### ISSUE THREAD

**Issue by CRYSTAF** [Kramar1337/GenshinImpact-AHK-flex#14]
Можно добавить автоматизацию сбора наград с экспедиций и установку персонажей. А конкретную настройку автоматизации можно добавить не через гуи, а через конфиг.

**Comment by Kramar1337** [comment]
уже не первый кто предлагает такую функцию
добавлять настраиваемый через конфиг это: геморно для меня, неудобно для других, бессмысленно по тому что есть аналоги похожих скриптов у других челов
попробую сделать чтото универсальное без настроек(для всех разрешений, регионов и тд), если не получится то не буду добавлять.
