### ISSUE TITLE
Проблема с выбором конкретного пункта и установки драйвера

### ISSUE THREAD

**Issue by FesT0** [Kramar1337/GenshinImpact-AHK-flex#15]
![image](https://user-images.githubusercontent.com/34135595/162427710-7a307413-99b5-4cac-8786-3a0087351e8b.png)
1.Не записывается драйвер
2. Не могу выбрать другую карту,другой способ взаимодействия,кроме SENDinput,после нажатия Pick
![image](https://user-images.githubusercontent.com/34135595/162428032-08869d04-c9d3-46fe-be01-b78de65118a4.png)
Последний AHK+все модули установлены

**Comment by FesT0** [comment]
![image](https://user-images.githubusercontent.com/34135595/162429306-51c0195f-880b-43bc-b479-7b123695ffa1.png)

**Comment by Kramar1337** [comment]
Описание устарело, позже переделаю.
Драйвер установлен верно, все ок.
Прост не выполнены условия 3го пункта в описании а конкретнее:
"нажимаем "WR" в обоих случаях и закрываем скрипт"
Скрипт устанавливающий драйвер определяет ВИД и ПИД а кнопка "WR" записывает их в "data\genConfig.ini"
[Extra]
KeyboardVID=0x1234
KeyboardPID=0x1234
MouseVID=0x1234
MousePID=0x1234

На всякий случай уточняю: 99% скрипта все равно работают на SenInput режиме и драйвер нужен для безопасной стрельбы с лука(контроля отдачи!), это его единственное назначение.

**Comment by Kramar1337** [comment]
кнопка "Pick" выбирает
кнопка "Save" применяет и перезагружает скрипт

**Comment by FesT0** [comment]
Понял,случайно не сталкивался с проблемой,что не работали некоторые скрипты. Tooltip Macro key не хочет показывать,что включено или нет. Также Num'ы не отключают банихоп и т.п.

**Comment by Kramar1337** [comment]
"Tooltip Macro key" подсказка на 0.5 сек какой выбран макрос
![image](https://user-images.githubusercontent.com/73392036/162502869-032c96a6-3b16-41c1-add2-1d4092188df2.png)

**Comment by Kramar1337** [comment]
Numpad 0 - Включить/отключить банихоп
первое нажатие отключает бхоп, повторное нажатие включает

**Comment by Kramar1337** [comment]
если бхоп отключен на главной, вкладка "бинды" то Numpad 0 не дает никакого эффекта

**Comment by Kramar1337** [comment]
если нампад клавиатура не работает то ее необходимо включить на клавиатуре кнопка "numlock"
