### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by CRYSTAF** [Kramar1337/GenshinImpact-AHK-flex#17]
Предлагаю небольшую приятную функцию. Кнопку включения и выключения Bhop'a можно разделить на две функции, а именно: в одном состоянии это будет Bhop, а в другом спам клавишей пробел, как тот же F для сбора предметов или Z для диалогов, чтобы можно было чуть быстрее взбираться на горы.

**Comment by Kramar1337** [comment]
bhop - это старый стиль распрыжки из квейка, халвы или кс
Здесь bhop делает все тоже самое, спамит пробел чтобы игрок распрыгивался и не терял скорость после рывка(даже если кончилась стамина)
 
Рофл в том что изначально bhop задумывался для быстрого открывания планера при прыжке, для этого я его и использую. Но в теории им нужно распрыгиваться не теряя скорость(для этого его и используют все остальные челы), а также ползать по стенам просто зажав пробел.

Дак о какой функции идет речь? bhop и так по скалам работает, просто залезь на скалу и зажми пробел. Также в меню  регулируется задержка перед срабатыванием для Казуха плееров
