### ISSUE TITLE
N2CD Hu Tao Dash Cancel

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/GenshinImpact-AHK-flex#18]
Наткнулся на сайте BotMek
![n2cd hu tao dash cancel](https://user-images.githubusercontent.com/6598192/187050916-986d9b6c-156d-4565-b457-24623398635c.png)

**Comment by Kramar1337** [comment]
я на геншин забил (отложил до выхода всей сумеру), ушел играть в Tower of fantasy и писать скрипты уже для TOFа. хорошо конечно что скрин с готовыми таймингами, но по хорошему нужно расчихлять пользовательский сервер + читы на бесконечные спелы и год мод чтобы калибровать скрипт, максимально не хочу этим заниматься. 
Скрин сохранил, когда нибудь потом добавлю
