### ISSUE TITLE
Rapid Fire

### ISSUE THREAD

**Issue by TheHooligan1337** [Kramar1337/GenshinImpact-AHK-flex#2]
Rapid fire in settings isn't working? And it's greyed out in the menu.  Sorry I don't speak russian so im using google translate.

Не работает скорострельный огонь в настройках? И он в меню неактивен. Извините, я не говорю по-русски, поэтому использую гугл-переводчик.
![klee](https://user-images.githubusercontent.com/76761388/103335048-fe48c680-4a30-11eb-8c43-c9e6bba8a784.png)

**Comment by TheHooligan1337** [comment]
Я вошел в файл конфигурации и установил для него значение 1 из 0 - теперь он включен, но по-прежнему не работает с Rbutton?

**Comment by Kramar1337** [comment]
Задумка:
Простая стрельба из лука с возможностью выбора режима: 
1. слабые и быстрые атаки
2. сильные и медленные
Реализация:
Скрипт часто ошибался и был удален. В графическом интерфейсе(GUI) остались переключатели.(мне лень их чистить)
Итог:
Функция была удалена.

Idea:
Simple archery with a choice of modes:
1.weak and fast attacks
2. strong and slow
Implementation:
The script was often mistaken and was removed. There are still switches in the GUI. (I'm too lazy to clean them)
Outcome:
The feature has been removed.
