### ISSUE TITLE
Hu Tao C1 Dash cancel recalibration

### ISSUE THREAD

**Issue by odano27** [Kramar1337/GenshinImpact-AHK-flex#21]
The timings provided by the previous suggestion don't work at all. Only works if done manually, not using AHK.
Below is my suggestion:

Loop
{
		GetKeyState, SSpaceStateAA, %key_animcancel%, P
		If SSpaceStateAA = U
			break
	SendInput {vk1}
	Sleep 180	
		GetKeyState, SSpaceStateAA, %key_animcancel%, P
		If SSpaceStateAA = U
			break
	SendInput {vk1}
	Sleep 125
		GetKeyState, SSpaceStateAA, %key_animcancel%, P
		If SSpaceStateAA = U
			break
	SendInput {vk1 Down}
	Sleep 300
	SendInput {vk1 up}
		GetKeyState, SSpaceStateAA, %key_animcancel%, P
		If SSpaceStateAA = U
			break
	Sleep 50
	SendInput {vkA0 Down}
	Sleep 50
	SendInput {vkA0 up}
	SendInput {vk41}
	Sleep 100
	SendInput {vk44}
	Sleep 100
		GetKeyState, SSpaceStateAA, %key_animcancel%, P
		If SSpaceStateAA = U
			break
	SendInput {vk41}
	Sleep 100
	SendInput {vk44}
	Sleep 100
}

Tested in the abyss against ruin grader (Руинный молотильщик). 9N2CD inconsistently, usually 7N2CD + 2N1CD. Can provide showcase if needed.

**Comment by Kramar1337** [comment]
updated
