### ISSUE TITLE
Ganyu more efficient key combination suggestion

### ISSUE THREAD

**Issue by odano27** [Kramar1337/GenshinImpact-AHK-flex#27]
```
	$~lbutton:: ; hotkey
	start := a_tickcount + 1775 ; set variable to be tickcount + delay
	while(GetKeyState("lbutton","P")) ; hotkey
	{
		if (a_tickcount > start && jopa17) 
		{
			SendInput {vk1 up}
			sleep 225
			SendInput {vk1 down}
			start := a_tickcount + 1775 ;reset the delay
		}
	}
```

A more efficient way to use Ganyu charged shots. However, this method does not enter aim mode (press R).
[Demo](https://imgur.com/a/IAhezTP). The first method is ~20% faster but requires more skill to aim.
Note that lbutton should be replaced with the hotkey.

**Comment by Kramar1337** [comment]
I added this script to the general bunch of specific macros. To activate it, set the configuration file "genConfig.ini" parameter "OldMacroBackVar=21"
Macro selection "Alt + Numpad 4 - Other macros (genConfig.ini)"
Activation "V - MacroKey"
