### ISSUE TITLE
Auto Exit false alarm.

### ISSUE THREAD

**Issue by CRYSTAF** [Kramar1337/GenshinImpact-AHK-flex#28]
Auto exit конечно фича полезная, но из-за того, что у некоторых людей геншин запускается дольше 3х секунд, то мне приходится по 3-4 раза его запускать, пока не открылся геншин. По нормальному лучше конечно сделать так, чтобы функция срабатывала именно после пропадания процесса геншина из диспетчера задач или списка процессов, а не просто из-за его отсутствия.

**Comment by Kramar1337** [comment]
добавил проверку процесса и +1 секунда
