### ISSUE TITLE
Genshi AHK Flex v4 Не работает

### ISSUE THREAD

**Issue by jjimwilliamss** [Kramar1337/GenshinImpact-AHK-flex#3]
Скрипт запустился, но никакие скрипты не работают. В частности интересует пропуск диалогов и bhop, и тот не захотел работать. В чём может быть проблема?

**Comment by Kramar1337** [comment]
у меня все режимы работают а вот у друга винда свежее и тоже были проблемы, как вариант переключиться в режим "WinApi" в настройках и запуск от админа, другу помогло

**Comment by Kramar1337** [comment]
Если не помогло то:
Переустановить автохоткей, в настройках установщика выставить все галочки в положение вкл.
Запускать скрипт от имени администратора, правым кликом и выбор запуск от админа, если такого пункта в контекстном меню нет то перейти в папку с автохоткеем "C:\Program Files\AutoHotkey" и каждый .exe протыкать в свойствах Совместимость=>Всегда запускать от админа
Открыть Genshi AHK Flex выбрать меню Безопасность=>режим ввода=>WinApi=>Pick=>Save, закрыть и открыть снова от админа.

Возможно чтото блокирует работу скрипта... или ошибка с кодировками гитхаба, можно попробовать старый Бхоп скрипт:
Правым кликом мышки по пустой области на рабочем столе, Создать=>Autohotkey скрипт
Открыть через блокнот созданный файл и вставить следующий код, сохранить и запустить от админа, если даже такой простой скрипт не будет работать то я тут ничем не помогу.

F10:: Hotkey, *~$Space, Toggle

*~$Space::
Sleep 1
Loop
{
    GetKeyState, SpaceState, Space, P
    If SpaceState = U
        break 
    Sleep 1
    Send, {Blind}{Space}
}
return

End::
ExitApp
