### ISSUE TITLE
Список проблем, которые я нашел

### ISSUE THREAD

**Issue by CRYSTAF** [Kramar1337/GenshinImpact-AHK-flex#4]
Итак, у меня за несколько месяцев использования вашего скрипта(около 4) накопилось несколько просьб к исправлению проблем в вашем скрипте.
1. При включенном Bhop'е нормально не работает полет(объясняю: когда ты спрыгиваешь допустим со скалы и нажимаешь полет, то все нормально, до тех пор, пока тебе не понадобится немного спустится, ты нажимаешь пробел, чтобы пролететь чуть вниз, у тебя закрывается планер и(внимание) тут же открывается, т.е. возможности нормально спустится нету), так же наблюдаются проблемы с Кадзухой, а именно когда на нем летишь к краешку горы я ,например, нажимаю "ешку", чтобы быстрее забраться, но из-за (так понимаю опять) Bhop'а он взлетает и опускается ровно на ту же высоту, что и взлетел (т.е. пользы в таком случае от "ешки" нету).
2. Фастлут стал работать очень "по-дурацки" он собирает предметы слишком медленно, мне уже проще тогда самому это делать, хотя одна из самых используемых "фич" в данном скрипте.
3. При включении карты через кнопку F1 не продумано то, что браузер может быть на втором экране и мышка в таком случае остаётся на первом (я понимаю, что может быть какой-нибудь конфликт с разрешениями экранов у игроков, так же понимаю, что далеко не у каждого есть 2 экран, но прошу заняться данной проблемой)
4. Зачем то убрали фото в оверлеями с реакциями стихий? (не понятно зачем)
Все доказать могу в дискорде (ҐӅჄԸŢĦᒈҊ ПNƘА#7777) демонстрацией экрана, так же, чтобы не быть "голословным" могу сказать то, что раньше в скрипте не было таких проблем, но из-за новых функций и обновления "оверлея" хотелось бы пользоваться новой версией скрипта, но постоянно приходится переключаться на старую. Интересно так же на сколько опасно использовать отключение CGI катсцен по сравнению с тем же фастлутом, который просто иммитирует нажатие клавиш на клавиатуре. Очень прошу исправить данные проблемы, т.к. накипело уже на столько, что решился написать данную "статью", если это можно таковым назвать. Надеюсь было не лень читать это. Если что - дополню

**Comment by Kramar1337** [comment]
На некст обнове(v4.3) все будет... или не все
1. По Бхопу, добавил возможность регулировать задержку срабатывания, частично решает эту проблему(я не играю с бхопом)
2. Фастлут всегда хорошо работал... НО... с добавлением WinApi режима пользователи у которых AutoHotkey неправильно установлен и не запущен от админа вообще ничего не работает!!, в установщике нужно выбирать 
"Custom installation" => "Unicode 64" => Все галочки => "Install" и попробовать разные режимы ввода, WinApi точно у всех работает(не рекомендовал бы его использовать по соображениям безопасности, сам с ним играю но понимаю что играю с огнем и нужно переходить на драйверный метод) античит в геншине уже год отдыхает и игнорирует многие вещи, бездну с паблик подрубом закрыл на фулл на пустом акке, жду бана, еще год ждать по ходу.
Фаст лут возможно скоро будет переработан в еще более быстрый(моментальный) 3 сундука открыл, вжух и пусто
3. Сначала не понял потом как понял, мышка будет прыгать в центр экрана, но окно игры все равно сворачивается если игра в фуллскрине, если перевести в оконный без рамки то прям топчик но в настройках такой функции нет и придется через параметры запуска+реестр, пример ярлыка:
"F:\Program Files\Genshin Impact\Genshin Impact Game\GenshinImpact.exe" -popupwindow
и реестр (Компьютер\HKEY_CURRENT_USER\Software\miHoYo\Genshin Impact) параметр "Screenmanager Is Fullscreen mode" поставить "0" все это будет норм работать на новой версии скрипта, проверил на 2560х1440 монике, думаю разницы нет там формула стоит, птом посмотрим.
4. Страничку с реакциями в оверлее вернул, не думал что ктото им будет пользоваться, там 0 информативности, не написано ни сколько кд наложения статуса, какая реакция какого порядка, что критует что нет и тд, страничка дрисня, ну мне не жалко могу вернуть, в идеале найти что более менее вменяемое.
5. По отключателю кастсцен, давно им не пользовался, он просто переименовывает 2 папки тут:
F:\Program Files\Genshin Impact\Genshin Impact Game\GenshinImpact_Data\StreamingAssets
былобы странно еслиб за переименование папок банили, за моды банят за переименование нет(сегодня нет, а завтра кто знает...)

**Comment by CRYSTAF** [comment]
Проблема в том, что такие функции как бхоп и фастлут раньше работали очень хорошо и безотказно. Зачем было их коробить, если они и так отлично работали - непонятно. На счёт выбора режима между sendinput winapi и еще 1, для чего надо было их добавлять если все итак работало хорошо не ясно. Конечно может быть это я чего то не понимаю и по вашим словам у меня не правильно установлен автохоткей, да и командовать созданием вашего скрипта я тоже не в праве, но если между ними(как минимум на глаз) нету разницы, то может быть лучше убрать их до лучших времен?

**Comment by CRYSTAF** [comment]
Так же решение проблемы с мышкой на 1 экране после инструкций тоже не решена. Когда геншин на 1 экране, а браузер с с картой на 2, то при нажатии на F1 мышка остаётся на 1 экране, на 2 экран она не переходит автоматом. Тобишь функция актуальна только для людей с 1 монитором, потому что быстрой комбинацией альт+таб, получается тоже самое, что и F1, единственное, что браузер с картой должен быть открыт.

**Comment by Kramar1337** [comment]
Вопрос с картой решится когда я обнову до тестирую, я вроде уточнил "все это будет норм работать на новой версии скрипта"
Вопрос с режимами ввода долго объяснять:
SendInput не работает у меня, но работает у других, причина в том что я отключил у себя UAC(контроль учетных записей(он же инпут лаг во всех играх, он же 90% проблем с установкой репаков)), у других он включен по стандарту
SendPlay изначальный режим на котором работали старые версии, не дружит с UACом, хорошо работал у меня и плохо у всех остальных
SendInput и SendPlay не поддерживают движение мыши по этому был добавлен WinApi и переписан весь скрипт, из за этого он вообще перестал у всех работать, причина в неправильной установке Автохоткея, его нужно переустановить со всеми галочками и Юникон64 версией.
Чем сложнее скрипт тем больше заморочек, по этому добавил разные режимы, если не робит 1й то пробовать 2й или 3й.

"Зачем было их коробить, если они и так отлично работали - непонятно" у меня и 2х моих друзей геншистов все норм работает значит ничего не трогаем. Кто не смог установить автохоткей следуя инструкции того проблемы, сделаю гифку установки и приложу к инструкции

**Comment by CRYSTAF** [comment]
Спасибо за объяснение так сказать. Теперь буду использовать SendPlay.

**Comment by CRYSTAF** [comment]
Спасибо за исправленный скрипт, теперь все работает отлично, как раньше👍
