### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TharakLoar** [Kramar1337/GenshinImpact-AHK-flex#5]
Awesome stuff!
1. Is it possible to make the Z a toggle that stops when the dialogue is over? Holding Z over a long dialogue can be annoying.

2. Also is it possible to use the "chest finder" when it is off cooldown, automatically or when holding F?

Thank you very much! :)

**Comment by Kramar1337** [comment]
Translated by google translator.
At the moment, the script is perfectly tuned and perfectly calibrated, I don't want to add extra functionality there and lose stability.
I plan to add auto fishing in the game update 2.1 and at this end work on the script and proceed to create a rage cheat.
1. Everything can be done on AHK, but how to make it convenient to use? There are many nuances:
- The button should be within the reach of the left hand, there are not many free keys left
- "Dialogue skip" toggle will interfere with in-game chat
- Some dialogues are short and it's just useless
- In some long dialogues, you need to select an answer option and "Dialogue skip" will automatically close the dialog, which will also be annoying
- Automatic "Dialogue skip" will be used as an active stream and will interfere with the overall work of the script
To skip long dialogues (there are few such dialogues in the game), you need to engage in ass fisting with the problems described above. Why do I need such difficulties, I do not understand?

2. Denied.
If you need an autosearch for chests, I can advise you to open the source code and replace all "SendInput {MButton down}" and "SendInput {MButton up}" with "SendInput {Z}"
"X - Witcher instinct" will turn into "Auto search for chests" double click on, single click off.
This function seems useless to me, I will not add it.

P.S. It looks a little messy and selfish to write three coders to add such pointless and twisted functionality to their scripts.
I will not smile politely and will be honest:
I make the script primarily for myself, I am open to suggestions and comments ... but I consider these (1 and 2) suggestions to be useless crap.

original post:
Переведено гугл переводчиком.
На данный момент скрипт идеально настроен и идеально откалиброван, я не хочу добавлять туда лишний функционал и терять стабильность.
Планирую добавить авто рыбалку в обновлении игры 2.1 и на этом завершить работу над скриптом и перейти к созданию рейдж чита.
1. На AHK можно сделать все, но как сделать это удобным в использовании? Есть много нюансов:
- Кнопка должна быть в пределах доступности левой руки, свободных клавиш там осталось не много
- "Dialogue skip" переключателем будет мешать использовать игровой чат
- Некоторые диалоги короткие и это просто бесполезно
- В некоторых длинных диалогах нужно выбирать вариант ответа и "Dialogue skip" автоматически будет закрывать диалог что также будет раздражать
- Автоматический "Dialogue skip" будет использоваться как активный поток и будет мешать общей работе скрипта
Чтобы пропускать длинные диалоги(таких диалогов мало в игре) нужно заниматься фистингом жопы с выше описанными проблемами. Зачем мне такие сложности я не понимаю?

2. Отказано.
Если нужен автопоиск сундуков могу посоветовать открыть исходный код и заменить все "SendInput {MButton down}" и "SendInput {MButton up}" на "SendInput {Z}"
"X - Witcher instinct" превратится в "Автопоиск сундуков" дабл клик вкл, сингл клик выкл.
Эта функция кажется для меня бесполезной, я не буду ее добавлять.

П.с. Это выглядит немного грязным и эгоистичным писать трем кодерам чтобы те добавили в свои скрипты такой бессмысленный и закрученный функционал.
Я не буду вежливо улыбаться и скажу честно:
Я делаю скрипт в первую очередь для себя, я открыт для предложений и замечаний... но эти(1 и 2) предложения я считаю бесполезным дерьмом.
