### ISSUE TITLE
крч предлагаю такую тему чтобы карта открывалась в окне поверх всего 

### ISSUE THREAD

**Issue by Shane216** [Kramar1337/GenshinImpact-AHK-flex#6]
хз как это реализовать  но единственное что знаю это вот этот параметр запуска для карты от михойо для гугла 
--app=https://webstatic-sea.mihoyo.com/app/ys-map-sea/?lang=ru-ru#/map/2?shown_types=71,70,64
и еще рамочка оч бесит противная такая у окна хз как убрать

**Comment by Kramar1337** [comment]
Касаемо рамки, сначала не понял потом как понял... Тыкал все подряд чтоб окно забагалось и игра перешла в оконный режим... Из множества попыток получилось только 1 раз.
Не могу понять причину появления такого бага и соответственно его решить, временное решение это Alt+Enter и окно вернется в нужную форму, но как сделать чтобы скрипт не допускал такого, хз.
Я мог бы добавить принудительное переключение в фуллскрин но тогда забагаются другие режимы. (переделаю, посмотрим что получится(в некст версии v4.4))


В заголовке темы указано "чтобы карта открывалась в окне поверх всего" немного не понял, скрипт и так максимизирует и активирует карту(она и так становится верхним окном)
Скрипт использует:
WinMaximize нужен для исправления проблемы
WinActivate сделать окно активным то есть сфокусироваться на нем.
Если сделать чтобы окно было !!всегда!! поверх всех окон, это приведет к куче проблем.

Параметр запуска "--app" как я понял запускает окно в "безменюшном" режиме(режим приложения).
Из за "особенностей" работы скрипта и максимальной совместимости, скрипт открывает карту в браузере по умолчанию, но в конфигурационном файле "genConfig.ini" предусмотрена возможность смены браузера и параметров запуска
Изменить 3 параметра:

BrauzerCheck=1
BrauzerPick=chrome.exe --app=https://webstatic-sea.mihoyo.com/app/ys-map-sea/
Map2toggle=1

Это не даст нужного результата(в окне поверх всего), но выглядит интересно.


Итог:
Рамки я попробую исправить.
Закреплять карту поверх всех окон - нет.

**Comment by Kramar1337** [comment]
а может о других рамка шла речь... Когда активна карта нажать F11 и карта будет в фуллскрине без рамок

**Comment by Shane216** [comment]
я плохо доношу мысль крч удобно ббыло б чтоб карта как видосик картинка в картинке была понимаеш)

**Comment by Shane216** [comment]
у меня к примеру нет второго монитора да, и не оч удобно свапаца каждый раз между окнами , а вот если б было как в режиме картинка в картинке в хроме идеально без рамочки окна прям кайф

**Comment by Kramar1337** [comment]
понял, добавлять не буду, по сути 2 строчки дописать и все, но там много нюансов с настройкой и больше вреда чем пользы
если нужно чтото закрепить поверх всех окон могу посоветовать использовать программу "PinMe!"

**Comment by Shane216** [comment]
^+SPACE:: Winset, Alwaysontop, , A 
я это использую где то откопал
