### ISSUE TITLE
Toggle?

### ISSUE THREAD

**Issue by TharakLoar** [Kramar1337/GenshinImpact-AHK-flex#7]
Hello!
Sorry to bother you again.
I have muscle pains on my hand/arm, especially when I click the same button multiple times, which makes playing the game a bit hard sometimes. Unfortunately, holding the F button for a long time also causes the same issue, although a bit better. I want to reduce the amount of clicks by setting F (and maybe Z) to a toggle. This way if there are like 30 items on the floor I can just click the button twice, instead of holding it for 30s while running around to pick them up.

You mentioned before it is a lot of work or you are not willing to do it, I have a bit of AHK programming knowledge, but not enough to find the lines related to these effects, especially since most of it is in Russian.
Could you point me to the lines related to the hotkey F and Z? The place where I could probably change it to a toggle. Line number would be enough. 

Thank you very much.

**Comment by Kramar1337** [comment]
Fastloot "F" ~1283 string (i am using new version and the line is different)
Search string "Metkakey_fastlyt:"

Dialogue skip "Z" ~1354 string
Search string "Metkakey_skipNPS:"

**Comment by TharakLoar** [comment]
Urgh... Spent 1hr+ trying to do this, no luck... Managed to do it roughly but the game was getting super lagged...
If I send you some coffee money (paypal?), could you possibly add this feature to F and Z? (maybe with a checkbox on the interface?) ;)

**Comment by Kramar1337** [comment]
run separately

Dialogue skip
https://pastebin.com/j7iKUi81

Fastloot
https://pastebin.com/7632uWgz

**Comment by TharakLoar** [comment]
Well well~~ That was beyond perfect! You are a genius! :)
Lemme get you a drink, send me your PayPal account or something I can donate.

**Comment by TharakLoar** [comment]
Yesterday I finally got through hours of useless dialogue in Inazuma on my secondary account... It was literally more than 1 hour just skipping as fast as possible... ridiculous waste of time...But made much easier with a toggle! My finger didn't hurt at all! :)

**Comment by TharakLoar** [comment]
I closed the threat by accident.

**Comment by Kramar1337** [comment]
I used PayPal only 1 time in 2018. The account is currently limited.
I wrote to support, the system is bad, I will wait 2-3 days for an answer

I can't know how international money transfers work.
If a simple Visa card number is enough, then:
Qiwi bank
Visa
4890494731528535

**Comment by TharakLoar** [comment]
I don't know what I can do with that number... lol
Let's wait for PayPal to answer you then :P

**Comment by Kramar1337** [comment]
Registering a new PayPal turned out to be easier than waiting for a response from support
PayPal
kramar1337@yandex.ru

**Comment by TharakLoar** [comment]
Sent it~~ Thank you for the hard work! :)

You don't need to fix it just because I sent money or anything, but if it's something easy to fix...
1. The "F" script dashes by itself while the toggle is on. (to test this, just toggle it on and run around a bit)
2. To the "F" script would it be easy to implement the "hold F" just like on the normal script (and also toggle it off, if on) and only double click turns the toggle on?
