### ISSUE TITLE
GenshinImpact-AHK-flex-main>Genshin AHK>data

### ISSUE THREAD

**Issue by Deencast** [Kramar1337/GenshinImpact-AHK-flex#9]
В файле pip instal ошибки.

Перепиши пожалуйста код, дописав py -m

Чтобы вот так получилось

py -m pip install asyncio
py -m pip install mido
py -m pip install keyboard
py -m pip install pynput
pause

Ибо не все шарят, а нужные файлы у них не скачиваются

**Comment by Kramar1337** [comment]
я питоном не занимаюсь(скрипт для лиры взял у другого чела) по этому сначала не понял, старый и новый вариант дают 1 результат, пошел читать что такое "py -m". На ру форуме, ТСа шлют нахyй 2 страницы подряд, на зарубежных после автоперевода сложно понять что имеют ввиду. На витруалке переустановил питона и батник перестал работать. Переустановил заново с галочкой "Add to PATH" и все заработало.(стоило об этом уточнить в инструкции к лире ветров, да)
Кароч "py -m" исправляет галочку установщика "Add to PATH".
Получается никто не пользовался моей лирой ветров за эти пол года.
Батник изменил, тикет закрываю
